::: {.content-hidden}
$$
{{< include sections/macros.tex >}}
$$
:::


# Welcome {.unnumbered}

These are the Lecture Notes of **Differential Geometry 661955** for 2024/25 at the University of Hull.
I will use this material during lectures. If you have any question or find any typo, please email me at


::: {.content-visible when-format="html"}
<div style="text-align: center;">
**[S.Fanzon@hull.ac.uk](mailto: S.Fanzon@hull.ac.uk)**
</div>
:::


::: {.content-visible when-format="pdf"}
\begin{center}
\textbf{
\href{mailto: S.Fanzon@hull.ac.uk}{S.Fanzon@hull.ac.uk}
}
\end{center}
:::


Up to date information about the course, Tutorials and Homework will be published on the University of Hull **Canvas Website**


::: {.content-visible when-format="html"}
<div style="text-align: center;">
**[canvas.hull.ac.uk/courses/73612](https://canvas.hull.ac.uk/courses/73612)**
</div>
:::


::: {.content-visible when-format="pdf"}
\begin{center}
\textbf{
\href{https://canvas.hull.ac.uk/courses/73612}{canvas.hull.ac.uk/courses/73612}
}
\end{center}
:::





## Digital Notes {.unnumbered}


::: {.content-visible when-format="html"}
Features of these digital notes:

- **Navigation** bar is available on the left
- A **search function** is available on the top-right 
- You can toggle **dark mode** on the top-right
- A **pdf** version of these notes is available to download on the top-right
:::



::: {.content-visible when-format="pdf"}
Digital version of these notes available at

\begin{center}
\textbf{
\href{https://www.silviofanzon.com/2024-Differential-Geometry-Notes/}{silviofanzon.com/2024-Differential-Geometry-Notes}
}
\end{center}
:::





## Readings {.unnumbered}

We will study curves and surfaces in $\R^3$, as well as some general topology. The main textbooks are:

- Pressley [@pressley] for differential geometry,
- Manetti [@manetti] for general topology.

Other good readings are the books:

- do Carmo [@do-carmo], a classic and really nice textbook 
- Abate, Tovena [@abate-tovena], for a more in depth analysis

I will assume some knowledge from Analysis 
and Linear Algebra. A good place to revise these topics are 
the books by Zorich [@zorich-1; @zorich-2]. 



## Visualization {.unnumbered} 

It is important to visualize the geometrical objects and concepts we are going to talk about in this module. Chapter 5 contains a basic Python tutorial to plot curves and surfaces. 
This part of the notes is **`not examinable`**.


If you want to have fun plotting with Pyhton, I recommend installation through [Anaconda](https://www.anaconda.com) or [Miniconda](https://docs.conda.io/en/latest/miniconda.html). 
The actual coding can then be done through 
[Jupyter Notebook](https://jupyter.org). Good references for scientific 
Python programming are [@johansson;@KSB-Python].   

If you do not want to mess around with Python, you can still visualize 
pretty much everything we will do in this module using 

- [Desmos](https://www.desmos.com)
- [CalcPlot3D](https://c3d.libretexts.org/CalcPlot3D/index.html)



::: {.callout-important}
You are not expected to purchase any of the above books. These lecture notes will cover 100% of the topics you are expected to known in order to excel in the Homework and Final Exam.
:::